version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Test
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8888:8000 
     
       
networks:
  django-network:
    driver: bridge