# Generated by Django 4.0.3 on 2022-04-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_postmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
