# Generated by Django 4.0.3 on 2022-04-04 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profile_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.ManyToManyField(db_index=True, related_name='block_relate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimage',
            field=models.URLField(blank=True),
        ),
    ]
