# Generated by Django 4.0.3 on 2022-04-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_block_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
